export const CONTACT_ACTIONS = {
  ON_FETCHING_CONTACTS: 'CONTACT_ACTIONS_ON_FETCHING_CONTACTS',
  ON_FETCHING_CONTACTS_SUCCESS: 'CONTACT_ACTIONS_ON_FETCHING_CONTACTS_SUCCESS',
  ON_FETCHING_CONTACTS_FAILURE: 'CONTACT_ACTIONS_ON_FETCHING_CONTACTS_FAILURE',

  ON_CREATE_CONTACT: 'CONTACT_ACTIONS_ON_CREATE_CONTACT',
  ON_CREATE_CONTACT_SUCCESS: 'CONTACT_ACTIONS_ON_CREATE_CONTACT_SUCCESS',
  ON_CREATE_CONTACT_FAILURE: 'CONTACT_ACTIONS_ON_CREATE_CONTACT_FAILURE',

  ON_UPDATE_CONTACT: 'CONTACT_ACTIONS_ON_UPDATE_CONTACT',
  ON_UPDATE_CONTACT_SUCCESS: 'CONTACT_ACTIONS_ON_UPDATE_CONTACT_SUCCESS',
  ON_UPDATE_CONTACT_FAILURE: 'CONTACT_ACTIONS_ON_UPDATE_CONTACT_FAILURE',

  ON_DELETE_CONTACT: 'CONTACT_ACTIONS_ON_DELETE_CONTACT',
  ON_DELETE_CONTACT_SUCCESS: 'CONTACT_ACTIONS_ON_DELETE_CONTACT_SUCCESS',
  ON_DELETE_CONTACT_FAILURE: 'CONTACT_ACTIONS_ON_DELETE_CONTACT_FAILURE',

  ON_FETCH_SINGLE_CONTACT: 'CONTACT_ACTIONS_ON_FETCH_SINGLE_CONTACT',
  ON_FETCH_SINGLE_CONTACT_SUCCESS: 'CONTACT_ACTIONS_ON_FETCH_SINGLE_CONTACT_SUCCESS',
  ON_FETCH_SINGLE_CONTACT_FAILURE: 'CONTACT_ACTIONS_ON_FETCH_SINGLE_CONTACT_FAILURE',

  ON_CHANGE_STATE: 'CONTACT_ACTIONS_ON_CHANGE_STATE',
}

export const TEAM_PROFILE_ACTIONS = {
  ON_FETCHING_PROFILES: 'TEAM_PROFILE_ACTIONS_ON_FETCHING_PROFILES',
  ON_FETCHING_PROFILES_SUCCESS: 'TEAM_PROFILE_ACTIONS_ON_FETCHING_PROFILES_SUCCESS',
  ON_FETCHING_PROFILES_FAILURE: 'TEAM_PROFILE_ACTIONS_ON_FETCHING_PROFILES_FAILURE',
}
